version: '2'
services:
    hamrofoodmandu-app:
        image: hamrofoodmandu
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://hamrofoodmandu-mysql:3306/hamrofoodmandu?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    hamrofoodmandu-mysql:
        extends:
            file: mysql.yml
            service: hamrofoodmandu-mysql
